

document.addEventListener("DOMContentLoaded", () => {
    const input = document.getElementById("search-bar");
    const submit = document.getElementById("search-button");
    const arrow = document.querySelector(".arrow");

    const listenToSearchBar = () => {
        submit.onclick = () => {
            console.log(input.value);
            searchForPokemon(input.value);
        }
    }

    const searchForPokemon = (pokemonName) => {
        const allPokemons = document.querySelectorAll(".pokemon-card");
        allPokemons.forEach(pokemonCard => {
            const pokemonObject = JSON.parse(pokemonCard.dataset.pokemon);
            const name = pokemonObject.name;
            getAllPokemons(name, pokemonName, pokemonCard);
        });
    }

    const getAllPokemons = (name, pokemonName, pokemonCard) => {
        if(pokemonName === '') {
            pokemonCard.style.display = "inline-block";
            return;
        }
        searchName(name, pokemonName, pokemonCard);
    }

    const searchName = (name, pokemonName, pokemonCard) => {
        if(!name.startsWith(pokemonName)) {
            pokemonCard.style.display = "none";
            return;
        }
        pokemonCard.style.display = "inline-block";
    }

    listenToSearchBar();

    // Listening to popstate event that has been 
    // generated by dispatchPopstateEvent() in render.js
    /* NOT WORKING CURRENTLY */
    window.onpopstate = () => {
        listenToSearchBar();
    }
})